name: test

on:
  workflow_run:
    workflows: ["build", "lint"]
    types:
      - completed

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
